# Generated by Django 5.2.12 on 2026-04-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Group Name')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Description')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Memo Group',
                'verbose_name_plural': 'Memo Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2, verbose_name='Priority')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='memos.memogroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
                'ordering': ['is_completed', '-is_pinned', 'due_date', '-updated_at'],
            },
        ),
    ]
