# Generated by Django 5.2.12 on 2026-04-07 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['is_completed', '-is_pinned', 'due_date', '-updated_at'], 'verbose_name': '备忘录', 'verbose_name_plural': '备忘录'},
        ),
        migrations.AlterModelOptions(
            name='memogroup',
            options={'ordering': ['name'], 'verbose_name': '备忘录分组', 'verbose_name_plural': '备忘录分组'},
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='memos.memogroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=120, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='memogroup',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='分组颜色'),
        ),
        migrations.AlterField(
            model_name='memogroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='memogroup',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='分组说明'),
        ),
        migrations.AlterField(
            model_name='memogroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='分组名称'),
        ),
    ]
